version: '3'
services:
              web:
                      image: flask
                      build: .
                      env_file:
                              - .env
                      environment:
                              GEMINI_API_KEY: ${GEMINI_API_KEY}
                              GEMINI_SERVER: ${GEMINI_SERVER}
                      ports:
                              - "8320:8320"
                      volumes:
                              - ./instance:/instance
                      restart: unless-stopped
