version: '3'
services:
              web:
                      image: flask
                      build: .
                      env_file:
                              - .env
                      ports:
                              - "8320:8320"
                      volumes:
                              - ./instance:/instance
                      restart: unless-stopped
